### ISSUE TITLE
哥  怎么获取字符呢，验证码的字符

### ISSUE THREAD

**Issue by zhushichuan** [aboutmydreams/pycapt#3]

**Comment by aboutmydreams** [comment]
filename,img = pycapt.train_img(
    my_str_list=['A','B','C','D','E'],
    width=30,
    height=32,
    num_of_str=1,
    font=30,
    xpan=3,
    ypan=2,
    rotate=15,
    noise_N=0.3,
    noise_Z=2,
    gray_value=255,
    font_family='ヒラギノ角ゴシック W8.ttc')
第一行的 filename 中就有字符串信息。
