### ISSUE TITLE
字体OSError: cannot open resource

### ISSUE THREAD

**Issue by Ipoon** [aboutmydreams/pycapt#8]
请问有字体（ヒラギノ角ゴシック W8.ttc）提供么

**Comment by aboutmydreams** [comment]
https://texwiki.texjp.org/?%E3%83%92%E3%83%A9%E3%82%AE%E3%83%8E%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88
也可以改一下代码，用一下自己电脑里的字体
